### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by derape** [snoopwpf/snoopwpf#127]
Clicking on "Delve BindingExpression" got me the exception:

Message: Index was outside the bounds of the array.
Stacktrace:
   at System.Windows.Data.MultiBindingExpression.TransferValue()
   at System.Windows.Data.MultiBindingExpression.Transfer()
   at System.Windows.Data.MultiBindingExpression.UpdateTarget(Boolean includeInnerBindings)
   at System.Windows.Data.MultiBindingExpression.AttachToContext(Boolean lastChance)
   at System.Windows.Data.MultiBindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by batzen** [comment]
Could you provide a repro for this?

**Comment by derape** [comment]
> Could you provide a repro for this?

I am able to reproduce that very easily but I am in an proprietary environment at the moment so I can't send you the whole source. What do you need for the invesigation?

**Comment by batzen** [comment]
A small sample application showcasing the issue would be enough. That's what I meant with "repro".

**Comment by batzen** [comment]
@derape ping

**Comment by batzen** [comment]
@derape ping

**Comment by derape** [comment]
Sorry, I wasn't able to reproduce it lately. If it happens again I will post an update
