### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by kentrob** [snoopwpf/snoopwpf#132]
I get this error whenever I drop crosshairs onto a WPF app. I built the SnoopOnly project in VS 2017 without errors. Thanks very much

Exception details:
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Snoop.Injector.Launch(WindowInfo windowInfo, Assembly assembly, String className, String methodName, String settingsFile) in D:\Temp\Projects\snoopwpf\Snoop\Injector.cs:line 35
   at Snoop.WindowInfo.Snoop() in D:\Temp\Projects\snoopwpf\Snoop\WindowInfo.cs:line 199

---
### Environment
- Snoop 2.11.0.0
- Windows 6.3.17134
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
Building only snoop is not enough to get the injection working. You have to build the snoop.sln. Will remove SnoopOnly during the weekend as you are the third person reporting this issue.

**Comment by kentrob** [comment]
Okay, thanks.
