### ISSUE TITLE
Trying to snoop an application got the below Exception.

### ISSUE THREAD

**Issue by mtalreja** [snoopwpf/snoopwpf#133]
----------------------EXCEPTION---------------------------------------------
System.Windows.Markup.XamlParseException: The type initializer for 'Snoop.Infrastructure.ComboBoxSettings' threw an exception. ---> System.ArgumentException: 'IsSnoopPart' property was already registered by 'ComboBox'.
   at System.Windows.DependencyProperty.RegisterCommon(String name, Type propertyType, Type ownerType, PropertyMetadata defaultMetadata, ValidateValueCallback validateValueCallback)
   at System.Windows.DependencyProperty.RegisterAttached(String name, Type propertyType, Type ownerType, PropertyMetadata defaultMetadata)
   at Snoop.Infrastructure.ComboBoxSettings..cctor() in C:\Users\Downloads\snoopwpf-master\snoopwpf-master\Snoop\Infrastructure\ComboBoxSettings.cs:line 46
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Snoop.SnoopUI.InitializeComponent() in C:\Users\Downloads\snoopwpf-master\snoopwpf-master\Intermediate\Snoop\Release\SnoopUI.xaml:line 1
   at Snoop.SnoopUI..ctor() in C:\Users\Downloads\snoopwpf-master\snoopwpf-master\Snoop\SnoopUI.xaml.cs:line 57
   at Snoop.SnoopUI.SnoopApplication() in C:\Users\Downloads\snoopwpf-master\snoopwpf-master\Snoop\SnoopUI.xaml.cs:line 170
   at Snoop.SnoopUI.GoBabyGo(String settingsFile) in C:\Users\Downloads\snoopwpf-master\snoopwpf-master\Snoop\SnoopUI.xaml.cs:line 146

**Comment by batzen** [comment]
That shouldn't happen.
Do you have a sample application i could reproduce this error with?

**Comment by batzen** [comment]
@mtalreja Any details on what you did?
