### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by NinjaServ** [snoopwpf/snoopwpf#134]
Tried to attach Snoop to an About Window.

Exception details:
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Snoop.Injector.Launch(WindowInfo windowInfo, Assembly assembly, String className, String methodName, String settingsFile) in x\Documents\GitHub\snoopwpf\Snoop\Injector.cs:line 35
   at Snoop.WindowInfo.Snoop() in x\Documents\GitHub\snoopwpf\Snoop\WindowInfo.cs:line 199

---
### Environment
- Snoop 2.11.0.0
- Windows 6.3.16299
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
You have to build the whole snoop.sln to get all required binaries. I already deleted the SnoopOnly.sln. Will also add a more detailed error message for that case.

**Comment by batzen** [comment]
Snoop 2.11 will contain details in the exception being thrown.
