### ISSUE TITLE
Errors require STA

### ISSUE THREAD

**Issue by miloush** [snoopwpf/snoopwpf#159]
Could it be possible to print the exception to the debug output before trying to show the error dialog?

```
Snooping application.
Starting snoop UI...
System.InvalidOperationException: The calling thread must be STA, because many UI components require this.
   at System.Windows.Input.InputManager..ctor()
   at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
   at System.Windows.Input.KeyboardNavigation..ctor()
   at System.Windows.FrameworkElement.FrameworkServices..ctor()
   at System.Windows.FrameworkElement.EnsureFrameworkServices()
   at System.Windows.FrameworkElement..ctor()
   at System.Windows.Controls.Control..ctor()
   at System.Windows.Window..ctor()
   at Snoop.ErrorDialog..ctor() in C:\projects\snoopwpf\Snoop.Core\ErrorDialog.xaml.cs:line 16
   at Snoop.ErrorDialog.ShowDialog(Exception exception, String title, String caption, Boolean exceptionAlreadyHandled) in C:\projects\snoopwpf\Snoop.Core\ErrorDialog.xaml.cs:line 48
   at Snoop.Infrastructure.SnoopManager.GoBabyGoForCurrentAppDomain(TransientSettingsData settingsData) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 137
   at Snoop.Infrastructure.SnoopManager.StartSnoopInstance(String settingsFile) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 97
   at Snoop.Infrastructure.SnoopManager.StartSnoop(String settingsFile) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 21
```

**Comment by batzen** [comment]
Will add the error to the debug output.
Any chance you could provide a repro application for this? It's quite strange that snoop tries to attach to an application that does not seem to be a WPF application.

**Comment by batzen** [comment]
Could you try the latest build from appveyor and see if your issue is really fixed?
There should be no error dialog if only one app domain fails.

You can grab the latest source build from https://ci.appveyor.com/project/batzen/snoopwpf/branch/develop/artifacts

**Comment by miloush** [comment]
Okay, so I confirm that if I choose to not snoop multiple domains, I get an error dialog now (with the error as expected above).

If I choose to debug multiple domains, I get the new output and a new exception I believe:
```
Starting snoop UI...
Could not snoop a specific app domain with friendly name of "DefaultDomain" in multiple app domain mode.
System.InvalidOperationException: The calling thread must be STA, because many UI components require this.
   at System.Windows.Input.InputManager..ctor()
   at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
   at System.Windows.Input.KeyboardNavigation..ctor()
   at System.Windows.FrameworkElement.FrameworkServices..ctor()
   at System.Windows.FrameworkElement.EnsureFrameworkServices()
   at System.Windows.FrameworkElement..ctor()
   at System.Windows.Controls.Control..ctor()
   at System.Windows.Window..ctor()
   at Snoop.Windows.SnoopBaseWindow..ctor() in C:\projects\snoopwpf\Snoop.Core\Windows\SnoopBaseWindow.cs:line 13
   at Snoop.SnoopUI..ctor() in C:\projects\snoopwpf\Snoop.Core\SnoopUI.xaml.cs:line 52
   at Snoop.Infrastructure.SnoopManager.<>c.<GetInstanceCreator>b__3_0() in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 155
   at Snoop.Infrastructure.SnoopManager.SnoopApplication(TransientSettingsData settingsData, Func`1 instanceCreator) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 177
   at Snoop.Infrastructure.SnoopManager.GoBabyGoForCurrentAppDomain(TransientSettingsData settingsData) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 130
'WINWORD.EXE' (CLR v4.0.30319: MyAddin.vsto|vstolocal): Loaded 'C:\Users\InformatiX-NB4K\AppData\Local\assembly\dl3\POJM97RW.QQ0\B0ROJTNR.DQQ\d21304c4\005419d9_5ed3d501\Snoop.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
System.InvalidCastException: Unable to cast transparent proxy to type 'Snoop.Infrastructure.SnoopManager'.
   at Snoop.Infrastructure.SnoopManager.StartSnoopInstance(String settingsFile) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 97
   at Snoop.Infrastructure.SnoopManager.StartSnoop(String settingsFile) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 22
```

**Comment by miloush** [comment]
The element I am trying to snoop is in `MyAddin.vsto|vstolocal` AppDomain by the way, i.e. not `DefaultDomain`. I wonder if rather than default or all domains, I could pick which AppDomain I want to snoop.

**Comment by batzen** [comment]
I added more error handling and more logging. Could you give it another try?
If you could provide a repro it would be easier to fix this ;-)

**Comment by miloush** [comment]
Indeed, got the message box in both cases now!

**Comment by batzen** [comment]
But were you able to see your elements?
Snoop should be able to work in the case you described.

**Comment by miloush** [comment]
No. I have a repro but it's basically same as in #116. I am running x64 Office though, could that make a difference?

**Comment by batzen** [comment]
You are right.
I broke the feature completely.
Will investigate and fix it.

**Comment by batzen** [comment]
After some investigation it seems as if Microsoft changed something on their side which currently blocks Snoop from working correctly.
The code i wrote for cross app domain to work made some assumptions which are not always true.
So it's not really Microsofts fault but mine because i didn't think about every possible way someone could create an app domain.
It will take me a few iterations to get it working correctly.
Will mention you here if i think that it's fixed.

**Comment by batzen** [comment]
@miloush This should work now. At least it works on my machine. ;-)
Could you give it another try?

**Comment by miloush** [comment]
@batzen it does indeed, thank you very much!
