### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by wilx01** [snoopwpf/snoopwpf#175]
I get the following on trying to switch to a 3D View, I have run both my App and Snoop with admin set

System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Media.Imaging.BitmapDecoder.get_IsDownloading()
   at System.Windows.Media.Imaging.BitmapSource.FreezeCore(Boolean isChecking)
   at System.Windows.PropertyMetadata.DefaultFreezeValueCallback(DependencyObject d, DependencyProperty dp, EntryIndex entryIndex, PropertyMetadata metadata, Boolean isChecking)
   at System.Windows.Freezable.FreezeCore(Boolean isChecking)
   at System.Windows.Freezable.Freeze()
   at System.Windows.Media.DrawingDrawingContext.DrawImage(ImageSource imageSource, Rect rectangle, AnimationClock rectangleAnimations)
   at System.Windows.Media.DrawingDrawingContext.DrawImage(ImageSource imageSource, Rect rectangle)
   at System.Windows.Media.DrawingContextDrawingContextWalker.DrawImage(ImageSource imageSource, Rect rectangle)
   at System.Windows.Media.RenderData.BaseValueDrawingContextWalk(DrawingContextWalker ctx)
   at System.Windows.Media.DrawingServices.DrawingGroupFromRenderData(RenderData renderData)
   at System.Windows.UIElement.GetDrawing()
   at Snoop.VisualTree3DView.MakeBrushFromVisual(Visual visual, Rect bounds) in C:\projects\snoopwpf\Snoop.Core\VisualTree3DView.cs:line 150
   at Snoop.VisualTree3DView.ConvertVisualToModel3D(Visual visual, Double& z) in C:\projects\snoopwpf\Snoop.Core\VisualTree3DView.cs:line 97
   at Snoop.VisualTree3DView.ConvertVisualToModel3D(Visual visual, Double& z) in C:\projects\snoopwpf\Snoop.Core\VisualTree3DView.cs:line 120
   at Snoop.VisualTree3DView.ConvertVisualToModel3D(Visual visual, Double& z) in C:\projects\snoopwpf\Snoop.Core\VisualTree3DView.cs:line 120
   at Snoop.VisualTree3DView.ConvertVisualToModel3D(Visual visual, Double& z) in C:\projects\snoopwpf\Snoop.Core\VisualTree3DView.cs:line 120
   at Snoop.VisualTree3DView.ConvertVisualToModel3D(Visual visual, Double& z) in C:\projects\snoopwpf\Snoop.Core\VisualTree3DView.cs:line 120
   at Snoop.VisualTree3DView..ctor(Visual visual) in C:\projects\snoopwpf\Snoop.Core\VisualTree3DView.cs:line 24
   at Snoop.Zoomer.HandleSwitchTo3D(Object target, ExecutedRoutedEventArgs args) in C:\projects\snoopwpf\Snoop.Core\Zoomer.xaml.cs:line 214
   at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandManager.ExecuteCommandBinding(Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)
   at System.Windows.Input.CommandManager.FindCommandBinding(CommandBindingCollection commandBindings, Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by batzen** [comment]
Any chance you could provide a repro for this?

**Comment by wilx01** [comment]
Hope this helps



________________________________

**Comment by wilx01** [comment]
Hi,
Sorry I just sent you the exe to reproduce, if you want the source let me know but it is basically from here. I made mini,um changes to the WindowsPresentation example from here, Or I can send you my source if needed

https://github.com/radioman/greatmaps


________________________________

**Comment by batzen** [comment]
This is nothing i can avoid in snoop, but you can in your application.
Your `GMapImageProxy` creates images by creating new decoders, those decoders can't be frozen but are tied to the current dispatcher thread.
The images created by those decoders can be frozen and are thus safe to access from different threads. But those images still refer to the unfrozen decoder. This access causes the exception.
The workaround i found was to directly assign the memory stream to a new `BitmapImage`.
You can use the following code in `GMapImageProxy` to make it work:
```
      public override PureImage FromStream(System.IO.Stream stream)
      {
         if (stream == null)
         {
            return null;
         }

         var type = stream.ReadByte();
         stream.Position = 0;

         ImageSource m = null;

         switch (type)
         {
            // PNG: 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A
            case 0x89:
            // JPG: 0xFF, 0xD8, 0xFF
            case 0xFF:
            // GIF: 0x47, 0x49, 0x46
            case 0x47:
            // BMP: 0x42, 0x4D
            case 0x42:
            // TIFF: 0x49, 0x49 || 0x4D, 0x4D
            case 0x49:
            case 0x4D:
               var bitmapImage = new BitmapImage
                  {
                     CacheOption = BitmapCacheOption.OnLoad,
                     CreateOptions = BitmapCreateOptions.IgnoreColorProfile
                  };
               bitmapImage.BeginInit();
               bitmapImage.StreamSource = stream;
               bitmapImage.EndInit();
               m = bitmapImage;
               break;

            default:
               Debug.WriteLine("WindowsPresentationImageProxy: unknown image format: " + type);
               break;
         }

         if (m == null)
         {
            return null;
         }

         var ret = new GMapImage { Img = m };
         if (ret.Img.CanFreeze 
            && ret.Img.IsFrozen == false)
         {
            ret.Img.Freeze();
         }

         return ret;
      }
```

**Comment by wilx01** [comment]
Thanks
I will try your suggestion tomorrow if I get time

Cheers

Martin
________________________________

**Comment by wilx01** [comment]
Thanks,
This worked like a charm!

Much appreciated,

Snoop is Amazing!

Martin

________________________________

**Comment by batzen** [comment]
Glad i could help.
