### ISSUE TITLE
Cross-thread exception in 3.0 alpha

### ISSUE THREAD

**Issue by BrannonKing** [snoopwpf/snoopwpf#176]
Dropped the crosshair on my geometry shape.

Exception details:
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Threading.DispatcherObject.VerifyAccess()
   at System.Windows.Media.CompositionTarget.VerifyAPIReadOnly()
   at System.Windows.Media.CompositionTarget.get_RootVisual()
   at Asi.Miscellaneous.Client.ViewModels.VisualTargetPresentationSource.get_RootVisual() in C:\Users\brannon.king\source\repos\mobius_g1\Projects\Asi.Miscellaneous.Client.ViewModels\VisualTargetPresentationSource.cs:line 62
   at Snoop.Infrastructure.SnoopManager.CheckForOtherDispatchers(Dispatcher mainDispatcher, TransientSettingsData settingsData, Func`1 instanceCreator) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 231
   at Snoop.Infrastructure.SnoopManager.SnoopApplication(TransientSettingsData settingsData, Func`1 instanceCreator) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 193
   at Snoop.Infrastructure.SnoopManager.<>c__DisplayClass4_0.<SnoopApplication>b__0() in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 198
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
### Environment
- Snoop 3.0.0.0
- Windows 6.3.18363
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
Could you provide a repro? That would make fixing it easier and faster.

**Comment by BrannonKing** [comment]
Create a StreamGeometry instance on the threadpool and freeze it. Then bind it to a WPF control.

**Comment by batzen** [comment]
It would be very helpful if you could provide a small sample project.

**Comment by batzen** [comment]
@BrannonKing ping

**Comment by batzen** [comment]
@BrannonKing ping

**Comment by BrannonKing** [comment]
I just spent two hours trying to reproduce the problem in a demo project. No luck.

Did you remove the CheckForOtherDispatchers method? I didn't see it in a search. Maybe the issue has been repaired already.

**Comment by batzen** [comment]
I improved large parts of the code some time ago.
Most of the code from `CheckForOtherDispatchers` is now in `InjectSnoopIntoDispatchers`.
Those improvements might indeed have fixed your issues by "accident" ;-)
