### ISSUE TITLE
Snoop 2.11 crash on starting the WPF application inspection

### ISSUE THREAD

**Issue by sandeepraju89** [snoopwpf/snoopwpf#184]
As soon as drag and drop the snoop cursor on WPF application, it is throwing error.

Error: Exception has been thrown by the target of an invocation.
Could not find file 'Snoop.resources'.

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not find file 'Snoop.resources'.
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetStream(String name, CultureInfo culture)
   at MS.Internal.Resources.ResourceManagerWrapper.GetStream(String name)
   at MS.Internal.AppModel.ResourcePart.EnsureResourceLocationSet()
   at MS.Internal.AppModel.ResourcePart.GetContentTypeCore()
   at System.IO.Packaging.PackagePart.get_ContentType()
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Snoop.ErrorDialog..ctor() in C:\projects\snoopwpf\Snoop\ErrorDialog.xaml.cs:line 20
   at Snoop.ErrorDialog.ShowDialog(Exception exception, String title, String caption, Boolean exceptionAlreadyHandled) in C:\projects\snoopwpf\Snoop\ErrorDialog.xaml.cs:line 49
   at Snoop.SnoopUI.GoBabyGoForCurrentAppDomain(String settingsFile) in C:\projects\snoopwpf\Snoop\SnoopUI.xaml.cs:line 161
   at Snoop.CrossAppDomainSnoop.CrossDomainGoBabyGo(String settingsFile) in C:\projects\snoopwpf\Snoop\Infrastructure\CrossAppDomainSnoop.cs:line 40
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at MessageHookProc(Int32 nCode, UInt64 wparam, Int64 lparam) in c:\projects\snoopwpf\managedinjector\injector.cpp:line 157

**Comment by batzen** [comment]
It looks like the default resource lookup exception thing from .net.
Does this crash your application or does snoop work normally after that exception?
Did you attach a debugger to the target process?

**Comment by sandeepraju89** [comment]
This is crashing my application.
I am facing same issue when i launch the application with debugger or just launching the application from click once.

**Comment by batzen** [comment]
That's very strange.
Could you try to reproduce your issue with the current preview version of snoop 3.0?
Does this happen with every application you try to snoop or just a single one?

**Comment by sandeepraju89** [comment]
Yes it is very strange. It is happening for me only and other team didn't had any issue.
And it popped up suddenly from last week.

Today i tried with 3.0 preview version and it is working fine.
Thank you.

**Comment by batzen** [comment]
So your issue is solved in snoop 3.0?

**Comment by sandeepraju89** [comment]
yes it is solved in 3.0

**Comment by batzen** [comment]
Good to hear that. Will close this then.

**Comment by sandeepraju89** [comment]
Yup sure.. thanks for your time.
