### ISSUE TITLE
Crash when snooping a WPF .net core app 3.1 

### ISSUE THREAD

**Issue by rCartoux** [snoopwpf/snoopwpf#194]
- Snoop version: release 3.0.0
- Crash when snooping a WPF .net core app 3.1 :
![image](https://user-images.githubusercontent.com/23009380/97150129-fab56c80-176d-11eb-9150-2ea0276e4df9.png)

- Stack trace:
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize
 ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section system.net. (C:\repos\SkyeBC\Output\InnoveoSkyeBusinessCanvas.dll.config line 3)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at Snoop.Core.Properties.Settings.get_ClearAfterDelve() in C:\projects\snoopwpf\Snoop.Core\Properties\Settings.Designer.cs:line 96
   at Snoop.Controls.PropertyInspector..ctor() in C:\projects\snoopwpf\Snoop.Core\Controls\PropertyInspector.xaml.cs:line 64

- Note: if I delete the exe config file of the snooped application and then restart it, Snoop works without issues.

**Comment by batzen** [comment]
Could you create a small repro application or attach the config file here? If the config file contains invalid elements there is little i can do in Snoop to prevent this, aside from rewriting the config system in Snoop (i already thought about this a few times already).

**Comment by rCartoux** [comment]
In the end we will just remove the config file, it was a left over from our migration to .NET Core 👍 

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.net>
    <defaultProxy useDefaultCredentials="true" />
  </system.net>
</configuration>
