### ISSUE TITLE
The calling thread cannot access this object because a different thread owns it.

### ISSUE THREAD

**Issue by maroldo26** [snoopwpf/snoopwpf#203]
**Place your issue description here.**

Exception details:
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Application.get_Windows()
   at Snoop.Data.Tree.ApplicationTreeItem.ReloadCore() in C:\projects\snoopwpf\Snoop.Core\Data\Tree\ApplicationTreeItem.cs:line 30
   at Snoop.Data.Tree.TreeItem.Reload() in C:\projects\snoopwpf\Snoop.Core\Data\Tree\TreeItem.cs:line 188
   at Snoop.Data.Tree.TreeService.Construct(Object target, TreeItem parent) in C:\projects\snoopwpf\Snoop.Core\Data\Tree\TreeService.cs:line 69
   at Snoop.Windows.SnoopUI.Load(Object newRoot) in C:\projects\snoopwpf\Snoop.Core\Windows\SnoopUI.xaml.cs:line 757
   at Snoop.Windows.SnoopMainBaseWindow.Inspect(Object rootToInspect) in C:\projects\snoopwpf\Snoop.Core\Windows\SnoopMainBaseWindow.cs:line 48
   at Snoop.Windows.SnoopMainBaseWindow.Inspect() in C:\projects\snoopwpf\Snoop.Core\Windows\SnoopMainBaseWindow.cs:line 39
   at Snoop.Infrastructure.SnoopManager.CreateSnoopWindow(TransientSettingsData settingsData, Dispatcher dispatcher, Func`1 instanceCreator) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 265
   at Snoop.Infrastructure.SnoopManager.<>c__DisplayClass8_1.<InjectSnoopIntoDispatchers>b__0() in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 320
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
### Environment
- Snoop 3.0.0.0
- Windows 6.3.18363
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
Could you provide a repro application for this?
