### ISSUE TITLE
Exception when trying to snoop application with invalid resource definitions inside ResourceDictionary

### ISSUE THREAD

**Issue by Mykullski** [snoopwpf/snoopwpf#207]
As of Snoop 3.0 (and Snoop.3.0.1-alpha0028) I cannot snoop at all. The latest 2 worked. Also no I cannot create a small repo because I have no idea where the error is. If I knew that I would fix it.

Exception details:
System.InvalidOperationException: Can only base on a Style with target type that is base type 'TextBoxBase'.
   at System.Windows.Style.Seal()
   at System.Windows.Style.System.Windows.ISealable.Seal()
   at System.Windows.StyleHelper.SealIfSealable(Object value)
   at System.Windows.ResourceDictionary.SealValue(Object value)
   at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at Snoop.Data.Tree.ResourceDictionaryTreeItem.ReloadCore() in C:\projects\snoopwpf\Snoop.Core\Data\Tree\ResourceDictionaryTreeItem.cs:line 68
   at Snoop.Data.Tree.TreeItem.Reload() in C:\projects\snoopwpf\Snoop.Core\Data\Tree\TreeItem.cs:line 185
   at Snoop.Data.Tree.ResourceDictionaryTreeItem.ReloadCore() in C:\projects\snoopwpf\Snoop.Core\Data\Tree\ResourceDictionaryTreeItem.cs:line 56
   at Snoop.Data.Tree.TreeItem.Reload() in C:\projects\snoopwpf\Snoop.Core\Data\Tree\TreeItem.cs:line 185
   at Snoop.Data.Tree.ResourceDictionaryTreeItem.ReloadCore() in C:\projects\snoopwpf\Snoop.Core\Data\Tree\ResourceDictionaryTreeItem.cs:line 56
   at Snoop.Data.Tree.TreeItem.Reload() in C:\projects\snoopwpf\Snoop.Core\Data\Tree\TreeItem.cs:line 185
   at Snoop.Data.Tree.TreeService.Construct(Object target, TreeItem parent) in C:\projects\snoopwpf\Snoop.Core\Data\Tree\TreeService.cs:line 67
   at Snoop.Data.Tree.ResourceContainerTreeItem.ReloadCore() in C:\projects\snoopwpf\Snoop.Core\Data\Tree\ResourceContainerTreeItem.cs:line 23
   at Snoop.Data.Tree.ApplicationTreeItem.ReloadCore() in C:\projects\snoopwpf\Snoop.Core\Data\Tree\ApplicationTreeItem.cs:line 30
   at Snoop.Data.Tree.TreeItem.Reload() in C:\projects\snoopwpf\Snoop.Core\Data\Tree\TreeItem.cs:line 185
   at Snoop.Data.Tree.TreeService.Construct(Object target, TreeItem parent) in C:\projects\snoopwpf\Snoop.Core\Data\Tree\TreeService.cs:line 67
   at Snoop.Windows.SnoopUI.Load(Object newRoot) in C:\projects\snoopwpf\Snoop.Core\Windows\SnoopUI.xaml.cs:line 762
   at Snoop.Windows.SnoopMainBaseWindow.Inspect(Object rootToInspect) in C:\projects\soopwpf\Snoop.Core\Windows\SnoopMainBaseWindow.cs:line 46
   at Snoop.Windows.SnoopMainBaseWindow.Inspect() in C:\projects\snoopwpf\Snoop.Core\Windows\SnoopMainBaseWindow.cs:line 37
   at Snoop.Infrastructure.SnoopManager.CreateSnoopWindow(TransientSettingsData settingsData, Dispatcher dispatcher, Func`1 instanceCreator) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 265
   at Snoop.Infrastructure.SnoopManager.<>c__DisplayClass2_0.<RunInCurrentAppDomain>b__0(TransientSettingsData data, Dispatcher dispatcher) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 182
   at Snoop.Infrastructure.SnoopManager.<>c__DisplayClass8_1.<InjectSnoopIntoDispatchers>b__0() in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 330
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
### Environment
- Snoop 3.0.0.0
- Windows 6.3.19042
- .NET Framework 4.0.30319.42000

**Comment by Mykullski** [comment]
This was burried
<Style x:Key="BlahStyle" BasedOn="{StaticResource BlahBlahStyle}" TargetType="{x:Type TextBoxBase}"/>

**Comment by batzen** [comment]
Snoop shouldn't crash because of this kind of issue but highlight it instead.
Will prevent the crash and add the highlighting to the planned diagnostics feature.
