### ISSUE TITLE
System.NotSupportedException

### ISSUE THREAD

**Issue by tgnorman** [snoopwpf/snoopwpf#232]
I had Snoop running on a window in the app I am debugging with VS.   Have closed the "snooped" app window, plus all snoop windows.  There are no snoop processes showing in TaskManager.
When I try to make a change in the app, such as click to change tab in the app window (which has several tabs), I get this error.
Even trying to move one of the app windows (it has a few open) ... I egt it.
Hitting the app's Close icon also triggers it...

I am at a loss to know why this happens, or how to escape from it, as there are no snoop processes running! 

Happy to help with further input if I can... 

Regards...

Exception details:
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at Snoop.Infrastructure.TrackedEvent.AddEventEntry(EventEntry eventEntry) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\EventTracker.cs:line 165
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

**Comment by batzen** [comment]
That's because parts of Snoop are still active even if you close all Snoop windows and Snoop here received events from a different thread than the control listing those events was created on.
As far as i remember if already fixed some things in this area for the next Snoop version, but i will have a closer look again to prevent this kind of issue.

**Comment by tgnorman** [comment]
Thanks… so, until a fix is implemented, is the solution to simply close all the app windows?  As I recall, a while back I could not even do that… as clicking the kill “X” icon just triggered the problem again – so, I was kinda stuck.

 

If that happens to me again, I can supply the trace if you like.

 

Cheers,

**Comment by batzen** [comment]
Sorry for not responding.
As soon as you run into this issue you can't do anything with your app anymore and will most likely have to use the task manager to end it.

This issue should not occur anymore with future versions of Snoop.
