### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by garzooma** [snoopwpf/snoopwpf#256]
Occurred when I installed Snoop (from .msi) on Windows 10, then tried editing a source file in Visual Studio 2019

Exception details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
### Environment
- Snoop 3.0.0.0
- Windows 6.3.19042
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
That's already fixed in the latest preview version.
You can download it from the CI build artifacts if you want.
