### ISSUE TITLE
Object reference not set to an instance of an object: This happens when I try to type in VS editor

### ISSUE THREAD

**Issue by dominoFire** [snoopwpf/snoopwpf#273]
**Place your issue description here.**

Exception details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
### Environment
- Snoop 3.0.0.0
- Windows 6.3.19043
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
That's already fixed in the next version. Will try to release next weekend.

**Comment by batzen** [comment]
And thanks for reporting this.

**Comment by batzen** [comment]
@dominoFire Had no time this weekend. Will try to get it done next week, but can't promise anything.
