### ISSUE TITLE
ILSpy Exception

### ISSUE THREAD

**Issue by cnayan** [snoopwpf/snoopwpf#28]
I was exploring ILSpy version 2.2.0.1706
While expanding FoldingMargin, I observed this exception.

Exception:

Message: Object reference not set to an instance of an object.
Stacktrace:
   at ICSharpCode.AvalonEdit.Folding.FoldingMarginMarker.OnRender(DrawingContext drawingContext)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Media.VisualBrush.LayoutCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by batzen** [comment]
This only happens if the FoldingMarginMarker is expanded after attaching snoop.
Steps to reproduce:
- Open ilspy
- Attach snoop
- Expand FoldingMarginMarker in ilspy
- Expand FoldingMarginMarker in snoop
-> Exception

If "Refresh" is hit in snoop before expanding FoldingMarginMarker in snoop there is no exception.

**Comment by batzen** [comment]
Created a PR in AvalonEdit as there nothing snoop can do to prevent the exception.
