### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by tom-englert** [snoopwpf/snoopwpf#298]
- Attached Snoop in multi-appdomain mode to application
- Inspected some controls
- Closed Snop

Now I can't type anything in the application, I get the following error on every key stroke:

Exception details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
### Environment
- Snoop 3.0.0.0
- Windows 6.3.19044
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
That should be fixed in version 4. Could you try the version from https://ci.appveyor.com/project/batzen/snoopwpf/branch/develop/artifacts and report back if it worked?
