### ISSUE TITLE
Ambiguous match found error while choosing the "shows only visuals with binding errors"

### ISSUE THREAD

**Issue by vborees** [snoopwpf/snoopwpf#30]
Hi Everybody,

I've got the following exception when trying to choose "shows only visuals with binding errors" option. Have to say, I am snooping quite large and complex application. Dows anybody know anything about this error? 

```
Message: Ambiguous match found.
Stacktrace:
   at System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetProperty(String name)
   at MS.Internal.ComponentModel.DependencyPropertyKind.get_IsDirect()
   at MS.Internal.ComponentModel.DependencyPropertyKind.get_IsAttached()
   at MS.Internal.ComponentModel.APCustomTypeDescriptor.GetProperties(Attribute[] attributes)
   at System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor.System.ComponentModel.ICustomTypeDescriptor.GetProperties(Attribute[] attributes)
   at System.ComponentModel.TypeDescriptor.GetPropertiesImpl(Object component, Attribute[] attributes, Boolean noCustomTypeDesc, Boolean noAttributes)
   at System.ComponentModel.TypeDescriptor.GetProperties(Object component, Attribute[] attributes)
   at Snoop.VisualItem.get_HasBindingError()
   at Snoop.SnoopUI.FilterBindings(VisualTreeItem node)
   at Snoop.SnoopUI.FilterBindings(VisualTreeItem node)
   at Snoop.SnoopUI.FilterBindings(VisualTreeItem node)
   at Snoop.SnoopUI.FilterBindings(VisualTreeItem node)
   at Snoop.SnoopUI.FilterBindings(VisualTreeItem node)
   at Snoop.SnoopUI.FilterBindings(VisualTreeItem node)
   at Snoop.SnoopUI.FilterBindings(VisualTreeItem node)
   at Snoop.SnoopUI.FilterBindings(VisualTreeItem node)
   at Snoop.SnoopUI.FilterBindings(VisualTreeItem node)
   at Snoop.SnoopUI.FilterBindings(VisualTreeItem node)
   at Snoop.SnoopUI.FilterBindings(VisualTreeItem node)
   at Snoop.SnoopUI.FilterBindings(VisualTreeItem node)
   at Snoop.SnoopUI.FilterBindings(VisualTreeItem node)
   at Snoop.SnoopUI.FilterBindings(VisualTreeItem node)
   at Snoop.SnoopUI.FilterBindings(VisualTreeItem node)
   at Snoop.SnoopUI.ProcessFilter()
   at Snoop.DelayedCall.Process(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)
```

**Comment by batzen** [comment]
I would need more details on this one.
A sample application where this happens would be nice, but as this issue is very old i guess you don't have that anymore.
Will close this issue. Feel free to re-open if you have more details.
