### ISSUE TITLE
An error has occured in developing .NET 6 Desktop App

### ISSUE THREAD

**Issue by dhq-boiler** [snoopwpf/snoopwpf#300]
I'm developing in an open source project called boiler's Graphics.

https://github.com/dhq-boiler/boiler-s-Graphics

The other day, I upgraded this project to .NET 6, but as soon as I upgraded, I got an error in Snoop.

![2021-12-14 (1)](https://user-images.githubusercontent.com/7916855/145922177-4d644ebb-3cb2-44ca-83dd-b2f833fdea8e.png)

Error details is below.
```
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize
 ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section system.data. (Z:\Git\boilersGraphics\boilersGraphics\bin\Release\net6.0-windows\boilersGraphics.dll.config line 34)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at Snoop.Core.Properties.Settings.get_UserDefinedPropertyFilterSets() in C:\projects\snoopwpf\Snoop.Core\Properties\Settings.Designer.cs:line 59
   at Snoop.Controls.PropertyInspector.get_UserFilterSets() in C:\projects\snoopwpf\Snoop.Core\Controls\PropertyInspector.xaml.cs:line 597
```

The file "Z:\Git\boilersGraphics\boilersGraphics\bin\Release\net6.0-windows\boilersGraphics.dll.config" is below.
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Reactive.Core" publicKeyToken="94bc3704cddfc263" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.0.3000.0" newVersion="3.0.3000.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Reactive.Interfaces" publicKeyToken="94bc3704cddfc263" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.0.1000.0" newVersion="3.0.1000.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Prism" publicKeyToken="40ee6c3a2184dc59" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-8.1.97.5141" newVersion="8.1.97.5141" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.1" newVersion="4.2.0.1" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.ComponentModel.Annotations" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.1.0" newVersion="4.2.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
<system.data>
    <DbProviderFactories>
      <remove invariant="System.Data.SQLite" />
      <add name="SQLite Data Provider" invariant="System.Data.SQLite" description=".NET Framework Data Provider for SQLite" type="System.Data.SQLite.SQLiteFactory, System.Data.SQLite" />
    </DbProviderFactories>
  </system.data></configuration>
```

Do you have any good ideas?

**Comment by batzen** [comment]
Which version of Snoop are you using?
Could you try the version from https://ci.appveyor.com/project/batzen/snoopwpf/branch/develop/artifacts and see if this still happens?
Does Snoop work after closing the error dialog?

**Comment by dhq-boiler** [comment]
I used Snoop v3.0.1.
I tried Snoop v4.0.0-alpha0403 and got the same result.

>Does Snoop work after closing the error dialog?
Yes.

**Comment by batzen** [comment]
Ok, then there is very little i can currently do to prevent this kind of issue.

Version 5, so the version after the next version, will come with a rewritten configuration/settings system.
The current one relies on the default configuration classes from .NET which cause the kinds of issues you are experiencing.

**Comment by batzen** [comment]
Rewrite of settings storage is tracked in #316
