### ISSUE TITLE
Error snooping .NET 7 app

### ISSUE THREAD

**Issue by SokoFromNZ** [snoopwpf/snoopwpf#390]
Hi,

I'm having troubles snooping a quite simple WPF app I'm building. When attaching Snoop I get this error message:
```
---------------------------
Error snooping
---------------------------
There was an error snooping the application.
Exception:
System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.Object,System.EventHandler]' to type 'System.Collections.Hashtable'.

   at Snoop.Infrastructure.Diagnostics.Providers.BindingLeakDiagnosticProvider.GetReflectPropertyDescriptorInfo() in C:\projects\snoopwpf\Snoop.Core\Infrastructure\Diagnostics\Providers\BindingLeakDiagnosticProvider.cs:line 132

   at Snoop.Infrastructure.Diagnostics.Providers.BindingLeakDiagnosticProvider.GetGlobalDiagnosticItemsInternal()+MoveNext() in C:\projects\snoopwpf\Snoop.Core\Infrastructure\Diagnostics\Providers\BindingLeakDiagnosticProvider.cs:line 28

   at Snoop.Infrastructure.Diagnostics.DiagnosticContext.AddRange(IEnumerable`1 items) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\Diagnostics\DiagnosticContext.cs:line 59

   at Snoop.Infrastructure.Diagnostics.DiagnosticContext.AnalyzeTree() in C:\projects\snoopwpf\Snoop.Core\Infrastructure\Diagnostics\DiagnosticContext.cs:line 99

   at Snoop.Windows.SnoopUI.Refresh() in C:\projects\snoopwpf\Snoop.Core\Windows\SnoopUI.xaml.cs:line 458

   at Snoop.Windows.SnoopUI.Load(Object newRoot) in C:\projects\snoopwpf\Snoop.Core\Windows\SnoopUI.xaml.cs:line 830

   at Snoop.Windows.SnoopMainBaseWindow.Inspect(Object rootObject) in C:\projects\snoopwpf\Snoop.Core\Windows\SnoopMainBaseWindow.cs:line 23

   at Snoop.Infrastructure.SnoopManager.CreateSnoopWindow(TransientSettingsData settingsData, DispatcherRootObjectPair dispatcherRootObjectPair, Func`1 instanceCreator) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 269

   at Snoop.Infrastructure.SnoopManager.<>c__DisplayClass2_0.<RunInCurrentAppDomain>b__0(TransientSettingsData data, DispatcherRootObjectPair dispatcherRootObjectPair) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 182

   at Snoop.Infrastructure.SnoopManager.<>c__DisplayClass8_0.<InjectSnoopIntoDispatchers>b__1() in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 398

   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

--- End of stack trace from previous location ---

   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)

   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)

   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)

   at System.Windows.Threading.Dispatcher.Invoke(Action callback)

   at Snoop.Infrastructure.SnoopManager.InjectSnoopIntoDispatchers(TransientSettingsData settingsData, Func`3 instanceCreator) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 396

   at Snoop.Infrastructure.SnoopManager.RunInCurrentAppDomain(TransientSettingsData settingsData) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 182
---------------------------
OK   
---------------------------

```

And then

```
---------------------------
Can't Snoop
---------------------------
Can't find a current application or a PresentationSource root visual.
---------------------------
OK   
---------------------------
```

Any Ideas?

The weird thing at the moment: If create a completely new project in VS2022 snooping works.

thx
Soko

**Comment by batzen** [comment]
This is already fixed in the next version of Snoop. You can either use the preview version from Chocolatey or from the CI build.
The final version will be published next week.

**Comment by SokoFromNZ** [comment]
Uhhh cool, thx!

**Comment by SokoFromNZ** [comment]
Can you point me to the EXE, ZIP or MSI download? Where can I find the CI build...

**Comment by SokoFromNZ** [comment]
Thx... found it here https://ci.appveyor.com/project/batzen/snoopwpf/build/artifacts
Downloaded the ZIP file.
And the error is fixed.
thx
