### ISSUE TITLE
This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.

### ISSUE THREAD

**Issue by Shrp77** [snoopwpf/snoopwpf#396]
**Snooping an application with multiple dispatchers (one snoop per dispatcher). Getting this error when I interact with the application. Snoop window is on the Debug Listener tab on the control I want to debug, but is NOT listerning.**

Exception details:
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at Snoop.Infrastructure.TrackedEvent.AddEventEntry(EventEntry eventEntry) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\EventTracker.cs:line 165
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
### Environment
- Snoop 3.0.0.0
- Windows 6.3.19045
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
Didn't notice you reported this for Snoop 3.0.
This was fixed in f2f08899b1d6c29f5479b869959d146e9774e5b8 which was part of version 4.0.
