### ISSUE TITLE
Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.Object,System.EventHandler]' to type 'System.Collections.Hashtable'.

### ISSUE THREAD

**Issue by lb7909** [snoopwpf/snoopwpf#432]
**Place your issue description here.**

Exception details:
System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.Object,System.EventHandler]' to type 'System.Collections.Hashtable'.
   at Snoop.Infrastructure.Diagnostics.Providers.BindingLeakDiagnosticProvider.GetReflectPropertyDescriptorInfo() in C:\projects\snoopwpf\Snoop.Core\Infrastructure\Diagnostics\Providers\BindingLeakDiagnosticProvider.cs:line 132
   at Snoop.Infrastructure.Diagnostics.Providers.BindingLeakDiagnosticProvider.GetGlobalDiagnosticItemsInternal()+MoveNext() in C:\projects\snoopwpf\Snoop.Core\Infrastructure\Diagnostics\Providers\BindingLeakDiagnosticProvider.cs:line 28
   at Snoop.Infrastructure.Diagnostics.DiagnosticContext.AddRange(IEnumerable`1 items) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\Diagnostics\DiagnosticContext.cs:line 59
   at Snoop.Infrastructure.Diagnostics.DiagnosticContext.AnalyzeTree() in C:\projects\snoopwpf\Snoop.Core\Infrastructure\Diagnostics\DiagnosticContext.cs:line 99
   at Snoop.Windows.SnoopUI.Refresh() in C:\projects\snoopwpf\Snoop.Core\Windows\SnoopUI.xaml.cs:line 458
   at Snoop.Windows.SnoopUI.HandleRefresh(Object sender, ExecutedRoutedEventArgs e) in C:\projects\snoopwpf\Snoop.Core\Windows\SnoopUI.xaml.cs:line 441
   at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandManager.HandleCommandBinding(Object sender, RoutedEventArgs e, CommandBinding commandBinding, Boolean execute)
   at System.Windows.Input.CommandManager.FindCommandBinding(CommandBindingCollection commandBindings, Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at 
Exception details truncated at 4000 chars.

---
### Environment
- Snoop 4.0.0.0
- Windows 6.3.22621
- .NET Framework 7.0.9

**Comment by lb7909** [comment]
I tried the Snoop 5.0.2, It's resolved. Sorry
