### ISSUE TITLE
Unable to attached snoop to application: unauthorized access exception

### ISSUE THREAD

**Issue by asfarley** [snoopwpf/snoopwpf#434]
I have a .NET 6 WPF application, and I seem to be unable to attach Snoop for debugging. The drop-down shows my application but when I click the binoculars, nothing happens. Same when I drop the crosshairs onto my application; no response. 

While running in Visual Studio 2022, I saw the following in the Output window when I tried to attach snoop:

```
'Vital-Sim.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files (x86)\Snoop\net5.0-windows\Snoop.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Starting snoop...
Loading transient settings file from "C:\Users\alexa\AppData\Local\Temp\tmpDC41.tmp"
'Vital-Sim.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.24\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Vital-Sim.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.24\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Vital-Sim Error: 0 : System.UnauthorizedAccessException: Access to the path 'C:\Users\alexa\AppData\Local\Temp\tmpDC41.tmp' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Snoop.Data.TransientSettingsData.LoadCurrent(String settingsFile) in C:\projects\snoopwpf\Snoop.Core\Data\TransientSettingsData.cs:line 71
   at Snoop.Infrastructure.SnoopManager.StartSnoopInstance(String settingsFile) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 69
   at Snoop.Infrastructure.SnoopManager.StartSnoop(String settingsFile) in C:\projects\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 54
```

This is on Windows 10, .NET 6, Snoop 5.1.0.

**Comment by batzen** [comment]
That's strange as Snoop just tries to read the temp file it just created itself.
Without having tried it the only case i can imagine this happens is that Snoop was started elevated and your process was not started elevated.
If that's not the case, it's definitely something permission related. Does your process do anything special in regards to permissions?

**Comment by batzen** [comment]
Just tried to reproduce your issue by running Snoop elevated and the target process non elevated, but it didn't cause the issue you are describing.

Is there anything special in your application regarding filesystem permissions?
When attaching Snoop creates a temp file, to transport settings to the target application, and once Snoop runs inside your process that file is read from disk.
I am not sure why that would fail with an UnauthorizedAccessException.
