### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by debabratamca** [snoopwpf/snoopwpf#451]
How to reproduce, this exception is coming if the application or visual studio stop debugging, and then it completely stop the visual studio execution that is very annoying.

**Place your issue description here.**

Exception details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
### Environment
- Snoop 3.0.0.0
- Windows 6.3.19045
- .NET Framework 4.0.30319.42000
![Capture](https://github.com/snoopwpf/snoopwpf/assets/10618047/17bcd180-56dc-4310-8ac4-e1c65d1266a1)

**Comment by batzen** [comment]
I don't fully understand when this happens.
Could you add a bit more information/context?

Have you tried a newer version of Snoop?
