### ISSUE TITLE
Issue with debugging applications that do not have an process path.

### ISSUE THREAD

**Issue by smaudet** [snoopwpf/snoopwpf#459]
Processes are not guaranteed to have an accessible process path, especially in the instance of a system execution (e.g. MSIExec).

See the original write up below, as well as a working code-fix:

--------------------------------------------------------------------------------------------------------------------------

**Running a custom version of v4.0.1, Snoop cannot create its window because it assumes it can create a settings file?**

New Snoop cannot open an MSI installer with a WPF UI. Old v4.0.1 could, after selectively applying a bunch of old v5.0.0 patches (trying to fix some theming problems), saw that the settings seems to be throwing an error. Possibly looks like the program assumes there is a file - there is not (MSI obscures the actual file path so this is a bad assumption).

System.Windows.Markup.XamlParseException: 'Provide value on 'System.Windows.Markup.StaticExtension' threw an exception.' Line number '130' and line position '31'. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Snoop.Core.Settings' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Snoop.Core.EnvironmentEx' threw an exception. ---> System.ComponentModel.Win32Exception: Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Snoop.Core.EnvironmentEx..cctor() in <buildlocation>\snoopwpf\Snoop.Core\EnvironmentEx.cs:line 14
   --- End of inner exception stack trace ---
   at Snoop.Core.SettingsHelper.GetApplicationSpecificSettingsFile() in <buildlocation>\snoopwpf\Snoop.Core\SettingsHelper.cs:line 39
   at Snoop.Core.SettingsHelper.GetSettingsFileForCurrentApplication() in <buildlocation>\snoopwpf\Snoop.Core\SettingsHelper.cs:line 48
   at Snoop.Core.Settings..ctor() in <buildlocation>\snoopwpf\Snoop.Core\Settings.cs:line 27
   at Snoop.Core.Settings..cctor() in <buildlocation>\snoopwpf\Snoop.Core\Settings.cs:line 30
   --- End of inner exception stack trace ---
   at Snoop.Core.Settings.get_Default()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Windows.Markup.StaticExtension.GetFieldOrPropertyValue(Type type, String name, Object& value)
   at System.Windows.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Snoop.Windows.SnoopUI.InitializeComponent() in <buildlocation>\snoopwpf\Snoop.Core\Windows\SnoopUI.xaml:line 1
   at Snoop.Windows.SnoopUI..ctor() in <buildlocation>\snoopwpf\Snoop.Core\Windows\SnoopUI.xaml.cs:line 60
   at Snoop.Infrastructure.SnoopManager.<>c.<GetInstanceCreator>b__5_0() in <buildlocation>\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 242
   at Snoop.Infrastructure.SnoopManager.CreateSnoopWindow(TransientSettingsData settingsData, DispatcherRootObjectPair dispatcherRootObjectPair, Func`1 instanceCreator) in <buildlocation>\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 254
   at Snoop.Infrastructure.SnoopManager.<>c__DisplayClass2_0.<RunInCurrentAppDomain>b__0(TransientSettingsData data, DispatcherRootObjectPair dispatcherRootObjectPair) in <buildlocation>\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 182
   at Snoop.Infrastructure.SnoopManager.<>c__DisplayClass8_0.<InjectSnoopIntoDispatchers>b__1() in <buildlocation>\snoopwpf\Snoop.Core\Infrastructure\SnoopManager.cs:line 398
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   
**Please do not close this as won't fix/invalid because of the version weirdness - I had to build this custom version to try figure out why v5.1.0 wasn't opening at all whereas v4.0.1 was able to open fine**

---
### Environment

- Snoop __v4.0.1-custom - roughly equivalent to 1b2f1896ec9ff1a39c5684cff9ca01e7961b128d minus a lot of the .net "upgrades".
- Windows 10
- .NET Framework unsure - running inside MSI

**Comment by smaudet** [comment]
Replacing the contents of EnvironmentEx:

```
public static class EnvironmentEx
    {
        public static readonly string CurrentProcessPath;
        public static readonly string CurrentProcessName;

        static EnvironmentEx()
        {
            using var currentProcess = Process.GetCurrentProcess();
            CurrentProcessName = currentProcess.ProcessName;
            string processPath = GetProcessPath(currentProcess);
            CurrentProcessPath = processPath;
        }

        private static string GetProcessPath(Process process)
        {
            try
            {
                return process.MainModule?.FileName ?? string.Empty;
            }
            catch (Win32Exception win32Exception)
            {
                Console.Error.WriteLine(win32Exception.StackTrace);
            }
            catch (Exception e)
            {
                Console.Error.WriteLine(e.StackTrace);
            }

            return string.Empty;
        }
    }
```

And fixing SettingsHelper starting on line 90:

```
            {
                string startPath = EnvironmentEx.CurrentProcessPath;
                string? currentPath = startPath;

                while (true)
                {
                    string path = Path.Combine(currentPath, SNOOP_SETTINGS_DIRECTORY_NAME);

                    if (Directory.Exists(path))
                    {
                        yield return path;
                    }

                    if (string.IsNullOrEmpty(currentPath))
                    {
                        break;
                    }

                    currentPath = Path.GetDirectoryName(currentPath);

                    if (string.IsNullOrEmpty(currentPath))
                    {
                        break;
                    }
                }
            }
```

Appears to fix the issue. This can be seen on dev - not sure if it will break the same yet, but the UI comes up where before it could not...
