### ISSUE TITLE
The operation was canceled by the user

### ISSUE THREAD

**Issue by VamsiPancheti** [snoopwpf/snoopwpf#466]
**Place your issue description here.**

Exception details:
System.ComponentModel.Win32Exception (0x80004005): The operation was canceled by the user
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Snoop.InjectorLauncherManager.Launch(ProcessInfo processInfo, IntPtr targetHwnd, String assembly, String className, String methodName, String transientSettingsFile) in C:\projects\snoopwpf\Snoop\InjectorLauncherManager.cs:line 77
   at Snoop.InjectorLauncherManager.Launch(ProcessInfo processInfo, IntPtr targetHwnd, MethodInfo methodInfo, TransientSettingsData transientSettingsData) in C:\projects\snoopwpf\Snoop\InjectorLauncherManager.cs:line 25
   at Snoop.ProcessInfo.Snoop(IntPtr targetHwnd) in C:\projects\snoopwpf\Snoop\ProcessInfo.cs:line 30

---
### Environment
- Snoop 5.0.0.0
- Windows 6.3.19045
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
A few more details would be helpful.

What exactly did you do?
